config/routes.rb
Rails.application.routes.draw do
  
  get "/email/:subscriber/:email", :to => "emails#show", :as => :read_email
  get "/subscribers" => redirect("/subscribers/new")
  
  get "/subscribe" => "subscribers#subscribe"
  
  resources :subscribers, :except => [:index,:edit,:update] do
    member do
      put :unsubscribe
      get :resubscribe
    end
  end
  
  namespace(:admin) do
    resources :subscribers do 
      get :unsubscribed, :on => :collection
      get :resubscribe,  :on => :member
      get :unsubscribe,  :on => :member
    end
    resources :emails do
      get :deliver, :on => :member, :path => 'send'
    end
  end

end

app/controllers/admin/emails_controller.rb
class Admin::EmailsController < Admin::BaseController
  
  resource_controller
  
  before_filter :get_subscribers, :only => [:new, :create, :edit, :update]
  before_filter :get_layouts, :only => [:new, :create, :edit, :update]
  
  new_action.before do
    @layouts = EmailLayout.all
  end
  
  create.success.wants.html {
    cookies[:current_email] = @email.token
    redirect_to admin_email_state_path("address") 
  }


  def edit
    @email = object
    @email.state = params[:state] if params[:state]
  end
  

  update.success.wants.html {
    @email.next!
    redirect_to admin_email_state_path(@email.state)
  }


  destroy.success.wants.js { render_js_for_destroy }


  
  
  
  

  def deliver
    @email = object
    sent, count = @email.deliver!
    if sent
      flash[:notice] = t('delivery_success', count)
    else
      flash[:error] = t('delivery_failed', count)
    end
    redirect_to admin_email_path(@email)
  end 

  private
  
    def get_subscribers
     @subscribers = Subscriber.active
    end
    
    def get_layouts  
      @layouts = EmailLayout.all
    end
    
    def object
      @object ||= Email.find_by_token(params[:id] || cookies[:current_email])
    end
    
    def collection
      params[:search] ||= {}
      params[:search][:meta_sort] ||= "subject.asc"
      @search = end_of_association_chain.metasearch(params[:search])
      @collection = @search.paginate(:per_page => Spree::Config[:admin_products_per_page], :page => params[:page])
    end
 
end

app/controllers/admin/subscribers_controller.rb
class Admin::SubscribersController < Admin::BaseController
  
  resource_controller
  
  destroy.success.wants.js { render_js_for_destroy }

  create.response do |wants|
    wants.html { redirect_to admin_subscribers_path }
  end
  
  update.response do |wants|
    wants.html { redirect_to admin_subscribers_path }
  end

  def resubscribe
    @subscriber = object
    if @subscriber.resubscribe!
      flash[:notice] = t('resubscribe_success')
    else
      flash[:error] = t('resubscribe_failed')
    end
    redirect_to request.referer
  end
    
  def unsubscribe
    @subscriber = object
    if @subscriber.unsubscribe!
      flash[:notice] = t('unsubscribe_success')
    else
      flash[:error] = t('unsubscribe_failed')
    end
    redirect_to request.referer
  end

  def unsubscribed
    params[:search] ||= {}
    params[:search][:unsubscribed_at_is_not_null] = true
    @subscribers = collection
    render :template => 'admin/subscribers/index'
  end

  private
  
    def object
      @object ||= Subscriber.find_by_token(params[:id])
    end
    
    def collection
      params[:search] ||= {}
      params[:search][:meta_sort] ||= "name.asc"
      unless params[:search].has_key?(:unsubscribed_at_is_not_null)
        params[:search][:unsubscribed_at_is_null] = true
      end    
      @search = end_of_association_chain.metasearch(params[:search])
      @collection = @search.paginate(:per_page => Spree::Config[:admin_products_per_page], :page => params[:page])
    end
    
end

app/controllers/emails_controller.rb
class EmailsController < Spree::BaseController
      
  include ActionView::Helpers::TagHelper
  include ActionView::Helpers::TextHelper
  
  def show
    @subscriber = Subscriber.find_by_token(params[:subscriber])
    @email      = Email.find_by_token(params[:email])
    if @email.recipients.include?(@subscriber.email)  
      @email_subject = @email.render(:subject, @subscriber)
      @text          = @email.render(:body,    @subscriber)
      @base_url      = "http://#{Spree::Config[:site_url]}"
      render :layout => 'email', :text => simple_format(@text)    
    else
      flash[:error] = t('unintended_email_view')
      redirect_to new_subscriber_path
    end
  end
  
end

app/controllers/subscribers_controller.rb
class SubscribersController < Spree::BaseController

  before_filter :get_subscriber, :only => [:show, :unsubscribe, :resubscribe]
  
  def new
    @subscriber = Subscriber.new
  end
  
  def show
    return redirect_to(new_subscriber_path) unless @subscriber && @subscriber.active?
  end
  
  def create
    @subscriber = Subscriber.new(params[:subscriber])
    if @subscriber.valid? && @subscriber.save
      flash[:notice] = t('subscribe_success')
      redirect_to new_subscriber_path
    else
      flash[:error] = t('subscribe_failed')
      render :action => 'new'
    end
  end
  
  def unsubscribe
    if @subscriber.email == params[:subscriber][:email] && @subscriber.unsubscribe!
      flash[:notice] = t('unsubscribe_success_public')
      redirect_to current_user ? account_path : new_subscriber_path
    else
      flash[:error]  = t('unsubscribe_failed_public')    
      redirect_to subscriber_path(@subscriber)
    end
  end
  
  def resubscribe
    if @subscriber.resubscribe!
      flash[:notice] = t('subscribe_success_public')
      redirect_to current_user ? account_path : subscriber_path
    else
      flash[:error]  = t('subscribe_failed_public')    
      redirect_to resubscribe_subscriber_path(@subscriber)
    end
  end
  
  def subscribe
    return redirect_to(new_subscriber_path) unless current_user
    @subsciber = Subscriber.find_by_email(current_user.email) rescue nil
    return redirect_to(account_path) if @subscriber && @subscriber.active?
    @subscriber = Subscriber.new(:email => current_user.email)    
    if @subscriber.save
      flash[:notice] = t('subscribe_success_public')
      redirect_to account_path
    else
      flash[:error]  = t('subscribe_failed_public')
      redirect_to new_subscriber_path
    end
    
  end
    
  private
  
    def get_subscriber
      @subscriber = Subscriber.find_by_token(params[:id])
      return redirect_to(new_subscriber_path) unless @subscriber
    end
  
end

app/controllers/user_registrations_controller_decorator.rb
UserRegistrationsController.instance_eval do 
  after_filter :create_subscriber  
end

UserRegistrationsController.class_eval do 
  def create_subscriber
    if @user && !@user.new_record? && params[:newsletter].to_i == 1
      @subscriber = Subscriber.create(:email => @user.email)            
    end
  end  
end

app/controllers/users_controller_decorator.rb
UsersController.instance_eval do
  
  before_filter :get_subscriber, :only => :show
  
end

UsersController.class_eval do
  
  def get_subscriber
    @subscriber = Subscriber.find_by_email(current_user.email) if current_user
  end
  
end

app/helpers/admin/emails_helper.rb
module Admin
  module EmailsHelper
      
    def progress_steps
      states = Email.state_machine.states.map &:name      
      steps = states.map do |state|
        current_index = states.index(@email.state.to_sym)
        state_index = states.index(state)
        text = t("email_states.#{state}")
        if state_index <= current_index
          link_to text, admin_email_state_path(state)
        else
          text
        end
      end
      content_tag('div', raw(steps.join("\n")), :class => 'progress-steps', :id => "checkout-step-#{@email.state}")
    end
      
  end
end

app/views/admin/email_layouts/_form.html.erb
<%- locals = {:f => f} %>

<% content_for :head do %>
  <%= stylesheet_link_tag 'admin/spree_mail' %>
  <script type="text/javascript">
  //<![CDATA[  
    $(document).ready(function() {
      $('div.selection a').click(function(evt) {
        evt.preventDefault();
        var a = $(this);
        var href = a.attr('href');
        var checkboxes = a.siblings('ul.select').find('input.checkbox');
        switch(href) {
          case '#select-all':        
            checkboxes.attr('checked', true);
            break;
          case '#deselect-all':
            checkboxes.attr('checked', false);        
            break;
        }
      });
      $('div.selection li').click(function(evt) {
        if (evt.target.type == 'checkbox') return true;
        evt.preventDefault();
        var cb = $(this).find('input[type=checkbox]');
        cb.attr('checked', cb.is(':checked') ? false : true);
      });
    });
  //]]>
  </script>  
<% end %>

<%= hook :admin_email_layout_form_fields, locals do %>
  
  <%= render "shared/error_messages", :target => @email_layout %>
      
  <%= f.field_container :name do %>
    <%= f.label :name, t("name") %><br />
    <%= f.text_field :name, :class => "title" %>
    <%= error_message_on :email_layout, :name %>
  <% end %>
  
  
<% end %>

app/views/admin/emails copy/_form.html.erb
<%- locals = {:f => f} %>

<% content_for :head do %>
  <%= stylesheet_link_tag 'admin/spree_mail' %>
  <script type="text/javascript">
  //<![CDATA[  
    $(document).ready(function() {
      $('div.selection a').click(function(evt) {
        evt.preventDefault();
        var a = $(this);
        var href = a.attr('href');
        var checkboxes = a.siblings('ul.select').find('input.checkbox');
        switch(href) {
          case '#select-all':        
            checkboxes.attr('checked', true);
            break;
          case '#deselect-all':
            checkboxes.attr('checked', false);        
            break;
        }
      });
      $('div.selection li').click(function(evt) {
        if (evt.target.type == 'checkbox') return true;
        evt.preventDefault();
        var cb = $(this).find('input[type=checkbox]');
        cb.attr('checked', cb.is(':checked') ? false : true);
      });
    });
  //]]>
  </script>  
<% end %>

<%= hook :admin_email_form_fields, locals do %>
  
  <%= render "shared/error_messages", :target => @email %>
  
  <div class="selection left">

    <h3><%= t('select_subscribers') %>:</h3>
    <%= link_to t('select_all'), "#select-all" %> / 
    <%= link_to t('deselect_all'), "#deselect-all" %>
    <ul class="select">
      <% @subscribers.each do |subscriber| %>
        <li class="checkbox">
          <%= check_box_tag "email[to][#{subscriber.id}]", subscriber.email, @email.recipients.include?(subscriber.email), :class => 'checkbox' %>
          <%= label_tag "email[to][#{subscriber.id}]", truncate("#{subscriber.name} <#{subscriber.email}>", :length => 37), :class => 'checkbox' %>
        </li>
      <% end %>
    </ul>
    <%= hidden_field_tag "email[to][0]", "" %>
  </div>
  
  <div class="right">
    
    <h3><%= t('message_details')%></h3>
    <%= f.field_container :subject do %>
      <%= f.label :subject, t("subject") %><br />
      <%= f.text_field :subject, :class => "title" %>
      <%= error_message_on :email, :subject %>
    <% end %>
    
    <%= f.field_container :body do %>
      <%= f.label :body, t('message_body') %><br />
      <%= f.text_area :body  %>
      <%= error_message_on :email, :body %>
    <% end %>
    
  </div>
  
<% end %>

app/views/admin/hooks/_subscribers_tab.html.erb
<%= tab :emails, :subscribers, :email_layouts, :label => "spree_mail" %>

app/views/admin/shared/_spree_mail_sub_nav.html.erb
<% content_for :sub_menu do %>
  <ul id="sub_nav">
    <%= hook :admin_email_sub_tabs do %>
      <%= tab :emails %>
      <%= tab :subscribers, :css_class => 'last' %>
    <% end %>
  </ul>
<% end %>

app/views/admin/subscribers/_form.html.erb
<%- locals = {:f => f} %>

<%= hook :admin_subscriber_form_fields, locals do %>
  
  <%= render "shared/error_messages", :target => @subscriber %>
  
  <%= f.field_container :name do %>
    <%= f.label :name, t('name') %><br />
    <%= f.text_field :name, :class => 'title' %>
    <%= error_message_on :subscriber, :name %>
  <% end %>
  
  <%= f.field_container :email do %>
    <%= f.label :email, t('email') %><br />
    <%= f.text_field :email, :class => 'title' %>
    <%= error_message_on :subscriber, :email %>
  <% end %>
  
<% end %>

app/views/admin/subscribers/_options.html.erb
<% if subscriber.active? %>
  <%= link_to t('unsubscribe'), unsubscribe_admin_subscriber_path(subscriber) %>
<% else %>
  <%= link_to t('resubscribe'), resubscribe_admin_subscriber_path(subscriber) %>
<% end %>

app/views/admin/subscribers/edit.html.erb
<%= render 'admin/shared/spree_mail_sub_nav' %>

<%= hook :admin_subscriber_edit_form_header do %>
  <h1><%= t('editing_subscriber') %></h1>
<% end %>

<%= hook :admin_subscriber_edit_form do %>
  <%= form_for(:subscriber, :url => object_url, :html => { :method => :put }) do |f| %>
    <%= render :partial => "form", :locals => { :f => f } %>

    <%= hook :admin_subscriber_edit_form_buttons do %>
      <%= render :partial => "admin/shared/edit_resource_links" %>
    <% end %>
  <% end %>
<% end %>

app/views/admin/subscribers/index.html.erb
<%= render 'admin/shared/spree_mail_sub_nav' %>

<div class='toolbar'>
  <ul class='actions'>
    <li>
      <p>
        <% if controller.action_name == 'unsubscribed' %>
          <%= button_link_to t('view_all_subscribers'), admin_subscribers_path %>
        <% else %>
          <%= button_link_to t('view_unsubscribed'), unsubscribed_admin_subscribers_path %>
        <% end %>        
        <%= button_link_to t('new_subscriber'), new_object_url, :icon => 'add' %>
      </p>
    </li>
  </ul>
  <br class='clear' />
</div>


<h1><%= t('listing_subscribers') %></h1>


<table class="index">
  <thead>
  <tr>
    <%= hook :admin_subscribers_index_headers do %>
      <th><%= sort_link @search, :name, t('name') %></th>
      <th><%= sort_link @search, :email, t('email') %></th>
      <th><%= hook :admin_subscribers_index_header_actions %></th>
    <% end %>
  </tr>
  </thead>
  <tbody>
    <% @subscribers.each do |subscriber|%>
      <tr id="<%= dom_id subscriber %>">
        <%- locals = {:subscriber => subscriber} %>
        <%= hook :admin_subscribers_index_rows, locals do %>
          <td><%=link_to subscriber.name || "(anonymous)", object_url(subscriber) %></td>
          <td><%= mail_to subscriber.email %></td>
        <% end %>
        <td>
          <%= hook :admin_subscribers_index_row_actions, locals do %>
            <%= link_to_edit subscriber %> &nbsp;
            <%= link_to_delete subscriber %> &nbsp;
            <%= render 'options', :subscriber => subscriber %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate(:previous_label => "&#171; #{t('previous')}", :next_label => "#{t('next')} &#187;") %>


<% content_for :sidebar do %>
<div class="box">
  <h3><%= t('search') %></h3>

  <% @subscriber = Subscriber.metasearch %>
  <%= form_for [:admin, @subscriber] do |f| %>
    <%- locals = {:f => f} %>
    <%= hook :admin_subscribers_index_search, locals do %>
      <p>
        <label><%= t 'name' %></label><br />
        <%= f.text_field :name_like, :size => 25 %>
      </p>
      <p>
        <label><%= t 'email' %></label><br />
        <%= f.text_field :email_like, :size => 25 %>
      </p>
    <% end %>
    <%= hook :admin_subscribers_index_search_buttons, locals do %>
      <p><%= button t('search') %></p>
    <% end %>
  <% end %>
</div>
<% end %>

app/views/admin/subscribers/new.html.erb
<%= render 'admin/shared/spree_mail_sub_nav' %>

<%= hook :admin_subscriber_new_form_header do %>
  <h1><%= t('new_subscriber') %></h1>
<% end %>

<%= hook :admin_subscriber_new_form do %>
  <%= form_for(:subscriber, :url => collection_url) do |f| %>
    <%= render :partial => "form", :locals => { :f => f } %>

    <%= hook :admin_subscriber_new_form_buttons do %>
      <%= render :partial => "admin/shared/new_resource_links" %>
    <% end %>
  <% end %>
<% end %>

app/views/admin/subscribers/show.html.erb
<%= render 'admin/shared/spree_mail_sub_nav' %>

<h1><%= t('show_subscriber') %></h1>

  <h5>Name:</h5>
  <h3><%= @subscriber.name %></h3>
  
  <h5>Email:</h5>
  <h3><%= mail_to @subscriber.email %></h3>

  <h5>Token:</h5>
  <p><%= @subscriber.token %></p>

<hr/>

<p>
  <%= link_to_edit @subscriber %> <%= t('or') %>
  <%= link_to t('back'), collection_url %>
</p>

app/views/hooks/_account_summary.html.erb
<h2><%= t('newsletter') %></h2>
<% if @subscriber && @subscriber.active? %>
  <p>
    <%= t('newsletter_signed_up') %><br/>
    <%= link_to t('unsubscribe'), subscriber_path(@subscriber) %>
  </p>    
<% else %>
  <p>
    <%= t('newsletter_signup') %><br/>
    
    <% if @subscriber %>  
      <%= link_to t('subscribe'), resubscribe_subscriber_path(@subscriber) %>
    <% else %>
      <%= link_to t('subscribe'), subscribe_path %>
    <% end %>

<% end %>

app/views/hooks/_footer_left.html.erb
<%= link_to t('sign_up_for_our_newsletter'), new_subscriber_path %>

app/views/hooks/_footer_right.html.erb
<%= form_for Subscriber.new do |form| %>
    <%= form.text_field :email, :class => 'title required' %>
    <%= form.submit t("sign_up") %>
<% end %>

app/views/hooks/_signup_checkbox.html.erb
<% if @user && @user.new_record? %>
  <p>
    <%= check_box_tag(:newsletter) %>
    <%= label_tag(:newsletter, t(:subscribe_newsletter_too)) %>
  </p>
<% end %>

app/views/layouts/email.html.erb
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
  <title><%= @email_subject %> - <%= Spree::Config[:site_name] %></title>
	<meta name="viewport" content="width = 640"/>
	
	<style type="text/css">
	  #content a { color: #5b8fb1; }
	</style>
	
</head>
<body style="min-width: 500px; margin: 0; padding: 15px; background-color: #ddd; background-image: url(<%= @base_url %>/images/mailer/background.jpg); background-repeat: repeat; font-family: Courier, serif; font-size: 14px; line-height: 19px; color: #575757; -webkit-text-size-adjust: 135%;">

  <%= yield %>

</html>
</body>

app/views/subscribers/_fields.html.erb
<p>
  <%= form.label :email %><br/>
  <%= form.email_field :email, :class => 'title required' %>
</p>
<p class="action">
  <%= form.submit t('sign_up') %>
</p>

app/views/subscribers/_unsubscribe.html.erb
<h1><%= t('unsubscribe_title') %></h1>

<p><%= t('unsubscribe_mail') %>:</p>

<%= form_for @subscriber, :url => unsubscribe_subscriber_path(@subscriber) do |form| %>
  <p>
    <%= form.label :email %>
    <%= form.text_field :email, :value => "" %>
  </p>
  <p>
    <%= form.submit t('unsubscribe') %> or
    <%= link_to t('cancel'), root_path %>
  </p>
<% end %>

app/views/subscribers/new.html.erb
<div class="left">
  
  <%= hook :subscriber_static_content do %>
    <h1><%= t('newsletter_sign_up') %></h1>
    <p><%= t('newsletter_text_signup') %></p>
  <% end %>
  
</div>

<div class="right">
  
  <%= hook :subscriber_sign_up_form do %>
    <%= render "shared/error_messages", :target => @subscriber %>
    <%= form_for @subscriber do |form| %>
      <%= render 'subscribers/fields', :form => form %>
    <% end %>
  <% end %>
  
</div>

<div class="clear">&nbsp;</div>

app/views/subscribers/show.html.erb
<h1><%= t('unsubscribe_title') %></h1>

<p><%= t('unsubscribe_mail') %>:</p>

<%= form_for @subscriber, :url => unsubscribe_subscriber_path(@subscriber.token) do |form| %>
  <p>
    <%= form.label :email %>
    <%= form.email_field :email, :value => "" %>
  </p>
  <p>
    <%= form.submit t('unsubscribe') %> or
    <%= link_to t('cancel'), :back %>
  </p>
<% end %>